spring:
  application:
    name: SpringBootRESTRepo
  datasource:
    url: jdbc:h2:mem:synechron
#    url: jdbc:mysql://localhost:8889/synechron
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
server:
  port: 8081