spring:
  application:
    name: SpringBootRESTRepo
  datasource:
    url: jdbc:h2:mem:synechron
#    url: jdbc:mysql://localhost:8889/synechron
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: ALWAYS
#      data-locations: classpath:data-test.sql
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
  profiles:
    active:
      - default
server:
  port: 8081

message: hello from default
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode= ALWAYS

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - custom
      base-path: /manage
  endpoint:
    health:
      show-details: ALWAYS
  server:
    port: 9090
